feat(css): parse css selectors (type, attr, nesting)
gosub-io/gosub-engine pull request #144
Opened 2023-10-16 08:44 UTC by neuodev

## Current State 

Parser can now parse all these selectors 

```css
            /* Links that start with "https://" and end in ".org" */
            a[href^="https://"][href$=".org"] {
                color: green;
            } 

            /* Links that end in ".org" */
            a[href$=".org"] {
                color: red;
            }

            /* Links with "cAsE" anywhere in the URL,
            with matching capitalization */
            a[href*="cAsE" s] {
                color: pink;
            }

            /* Links with "insensitive" anywhere in the URL,
            regardless of capitalization */
            a[href*="insensitive" i] {
                color: cyan;
            }

           /* Links with "example" anywhere in the URL */
            a[href*="example"] {
                background-color: silver;
            }

            /* Internal links, beginning with "#" */
            a[href^="#"] {
                background-color: gold;
            }

            a {
                color: blue;
            }

            ul > li {}  

            ul || li {}

            ul, li {}

            ul|li {}
            
            ul + li {}

            ul ~ li {}

```

2023-10-16 12:01 UTC, jaytaph approved these changes

2023-10-16 13:25 UTC, emwalker requested changes
Looks like one of the commits is failing checks.  Can you either squash the commits into a single commit and force push, or rebase and fix the checks on each commit?  This will help with `git bisect` in the future.

```sh 
$ make fix 
$ make test
```

2023-10-16 13:25 UTC, emwalker commented on src/css3/node.rs
> +}
Interesting name.  I look forward to seeing what you do with this enum.

2023-10-16 13:25 UTC, emwalker commented on src/css3/tokenizer.rs
> +        assert_eq!(tokenizer.has_more_tokens(), true);
Can you run `make fix` on this PR?  I'm wondering whether these changes will go back to what was there before.

2023-10-16 13:25 UTC, emwalker commented on src/lib.rs
> +pub mod css3;
Awesome.

2023-10-16 14:38 UTC, emwalker approved these changes

2023-10-16 16:09 UTC, blaumeise20 commented
What does `ul || li` do? Did I miss something here?

2023-10-16 19:21 UTC, Kiyoshika approved these changes

2023-10-16 19:25 UTC, merged

2023-10-20 06:45 UTC, blaumeise20 commented
> [Column Selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Column_combinator)

Oh, thanks. So we would be the first browser to support this? 😉